version: '2'

services:
# Start messaging broker
  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5672:5672"
      - "15672:15672" #Management Server
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"

# Start transformation worker
strokewidthtransform:
  image: maiduchuy/img-proc
  volumes: 
    - ./scripts/:/opt/open-ocr/
  dns: ["8.8.8.8"]
  links:
    - rabbitmq
  command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor img-proc"

# Start OCR worker
openocrworker:
  image: maiduchuy/open-ocr
  volumes: 
    - ./scripts/:/opt/open-ocr/
  dns: ["8.8.8.8"]
  links:
    - rabbitmq
  command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"

# Start http server
openocr:
  image: maiduchuy/open-ocr
  dns: ["8.8.8.8"]
  volumes: 
    - ./scripts/:/opt/open-ocr/
  links:
    - rabbitmq
  ports:
    - "9292:9292"
  command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"
